#!/bin/bash
#
# Toggles the GitHub remote origin from HTTPS to SSH and vice versa.
#
if [[ ! $(command -v git) ]]; then
  echo "Git is not installed."
  exit 1
fi
if [[ ! $(git remote -v 2> /dev/null) ]]; then
  echo "Not a git repository."
  exit 1
fi
GET=
REMOTES=$(git remote -v)
for REMOTE in $REMOTES; do
  if test $GET; then
    # If using HTTPS, switch to SSH.
    REPO=$(echo $REMOTE | cut -d'/' -f3)
    if [[ $REPO == 'github.com' ]]; then
      USER=$(echo $REMOTE | cut -d'/' -f4)
      PROJECT=$(echo $REMOTE | cut -d'/' -f5)
      git remote rm origin
      git remote add origin git@github.com:$USER/$PROJECT
      git remote -v
      exit 0
    fi
    # If using SSH, switch to HTTPS.
    REPO=$(echo $REMOTE | cut -d'@' -f2 | cut -d':' -f1)
    if [[ $REPO == 'github.com' ]]; then
      PROJECT=$(echo $REMOTE | cut -d':' -f2 | cut -d' ' -f1)
      git remote rm origin
      git remote add origin https://github.com/$PROJECT
      git remote -v
      exit 0
    fi
  fi
  if [[ $REMOTE == 'origin' ]]; then
    GET=1
  fi
done
